[package]
name = "cmd1"
version = "0.1.0"
authors = ["Pix <jvall@shaw.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
